[profile.default]
src = "src"
out = "out"
libs = ["lib"]

rpc_endpoints = {mainnet = "https://eth-mainnet.g.alchemy.com/v2/UUnnWhJdSk8fQt3D5h7kAZQNw8wY-PDx"}

# See more config options https://github.com/foundry-rs/foundry/tree/master/config